services:
  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/postgresql

  adminer:
    image: adminer:5.4.2
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  dbdata:
