services:
  always:
    image: busybox:1.37.0
    command: sh -c "echo 'Exiting successfully...' && sleep 2 && exit 0"
    restart: always

  on-failure:
    image: ongoonku/kuard-amd64:1
    ports:
      - "8080:8080"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 128M

  unless-stopped:
    image: busybox:1.37.0
    command: sh -c "echo 'Running...' && sleep infinity"
    restart: unless-stopped
