server {
    listen 80;
    server_name game-collection.local;

    location / {
        proxy_pass http://game-collection:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name samtris.local;

    location / {
        proxy_pass http://samtris:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
